version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0     
    steps:
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
       - run: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
          command: |
        - run: rm -rf node_modules/
        - run: ./jfrog rt npmi npm-virtual --build-name=circleci-npm-artifactory --build-number=$CIRCLE_BUILD_NUM
        - run: ./jfrog rt bce circleci-npm-artifactory $CIRCLE_BUILD_NUM
        - run: ./jfrog rt npmp npm-virtual --build-name=circleci-npm-artifactory --build-number=$CIRCLE_BUILD_NUM
        - run: ./jfrog rt bp circleci-npm-artifactory $CIRCLE_BUILD_NUM
