version: 2
jobs:
  build:
      docker:
        - image: circleci/node:8.9.0 
      working_directory: ~/repo
      steps:
        - run:
            name: Install jFrog CLI
            command: curl -fL https://getcli.jfrog.io | sh
        - run:
            name: Configure Artifactory
            branch: "master"
            command: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD --interactive=false
        - run: rm -rf node_modules/
        - run:
            name: NPM Install
            command: ./jfrog rt npmi npm-virtual --build-name=circleci-npm-artifactory --build-number=$CIRCLE_BUILD_NUM

