version: 2
jobs:
  build:
      docker:
        - image: circleci/node:8.9.0     
      steps:
        - run:
            name: Install jFrog CLI
            command: curl -fL https://getcli.jfrog.io | sh
        - run:
            name: Push to Artifactory
            branch: "master"
            command: |
              - ./jfrog rt c show
