version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0     
    steps:
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Configure jFrog CLI
          command: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD --interactive=false
      - run:
          name: Push to Artifactory	
          command: |
          - ./jfrog rt npmi npm-virtual --build-name=circleci-npm-artifactory --build-number=$CIRCLE_BUILD_NUM
          - ./jfrog rt bce circleci-npm-artifactory $CIRCLE_BUILD_NUM
          - ./jfrog rt npmp npm-virtual --build-name=circleci-npm-artifactory --build-number=$CIRCLE_BUILD_NUM
          - ./jfrog rt bp circleci-npm-artifactory $CIRCLE_BUILD_NUM
