version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0     
    steps:
      - run: curl -fL https://getcli.jfrog.io | sh
       - run: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
